name: Go formater
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' 
          
      - name: Run go fmt
        run: |
          echo "Running go fmt on current directory..."
          go fmt ./...
          echo "Formatting completed!"
        
